### ISSUE TITLE
Setup continuous deployment to PyPi

### ISSUE THREAD

**Issue by apsknight** [dsciitbbs/acl#2]
Currently, `acl` can be installed by `pip install acl-iitbbs` but it isn't in CD with this repo as of now. Look for the possibility to make it CD with this repo.

**Comment by PalAditya** [comment]
As per the **docs**:

```yaml
deploy:
  provider: pypi
  user: "__token__"
  password: "Your PyPI API token, including the pypi- prefix"
```
And for securing your token, first run:

```travis encrypt your-api-token --add deploy.password --com``` 

(as we are using travis-ci.com, not .org), followed by:
```yaml
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Your encrypted token"
```

Since you were the *original* owner of this project, would it be possible for you to add these changes to the .yml file to make it CD? Or would you rather have this issue tackled by someone else who wishes to learn how CI/CD works?

In case the second option holds, [here](https://docs.travis-ci.com/user/deployment/pypi/) is the full reference.
